    - name: 'Download Wordpress Linux '
      get_url:
        url:  'https://wordpress.org/wordpress-5.0.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
      
    - name: 'Descompactar'
      unarchive:
        src:  '/tmp/wordpress.tar.gz'
        dest: '/var/www'
        remote_src: yes
      become: yes 

    - name: 'Copiar arquivos'
      copy:
        src:  "{{ wp_wordpress_dir }}/wp-config-sample.php"
        dest: "{{ wp_wordpress_dir }}/wp-config.php"
        remote_src: yes
      become: yes   
    
    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path:  "{{ wp_wordpress_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
        - { regex: 'username_here', value: "{{ wp_user }}"}
        - { regex: 'password_here', value: "{{ wp_user_pass }}"}
        - { regex: 'localhost', value: "{{ wp_db_ip }}"}
      become: yes

    - name: 'Configura o apache para o wordpress'
      template:
        src:  '/vagrant/configs/ansible/roles/wordpress/templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes 
      notify:
        - restart apache  
