    - name: 'Instala pacotes de dependencia'
      apt: 
        name: ['mysql-server-5.6', 'python-mysqldb']
        state: latest
      become: yes

    - name: 'Cria o banco de dados'
      mysql_db: 
        name: "{{ wp_db_name }}"
        login_user: "{{ wp_login }}"
        state: present

    - name: 'Cria usuario no mysQl'
      mysql_user:
        login_user: "{{ wp_login }}"
        name: "{{ wp_user }}"
        password: "{{ wp_user_pass }}"
        priv: '{{ wp_db_name }}.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - "{{ wp_host_ip }}"

    - name: 'Conexoes do mysql'
      copy: 
        src: '/vagrant/configs/ansible/roles/mysql/files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - restart mysql
